### ISSUE TITLE
"NaN detected" when using 'attn_type': 'stochastic'

### ISSUE THREAD

**Issue by quilby** [kelvinxu/arctic-captions#14]
When I set attn_type to deterministic training works fine, when I set it to stochastic I get a 'NaN detected' error and the training halts.
Here is an example output:
```
$ python evaluate_coco.py 
Using gpu device 0: GeForce GTX TITAN Black
Using the following parameters:
{'lrate': 0.01, 'decay_c': 0.0, 'patience': 10, 'save_per_epoch': False, 'n_layers_init': 2, 'RL_sumCost': True, 'max_epochs': 5000, 'dispFreq': 1, 'attn_type': 'stochastic', 'alpha_c': 1.0, 'temperature': 1.0, 'n_layers_att': 2, 'saveto': 'my_caption_model.npz', 'ctx_dim': 512, 'valid_batch_size': 64, 'lstm_encoder': False, 'n_layers_lstm': 1, 'optimizer': 'adam', 'validFreq': 2000, 'dictionary': None, 'batch_size': 64, 'selector': True, 'n_words': 10000, 'dataset': 'coco', 'use_dropout_lstm': False, 'prev2out': True, 'dim': 1800, 'use_dropout': True, 'dim_word': 512, 'sampleFreq': 250, 'semi_sampling_p': 0.5, 'n_layers_out': 1, 'saveFreq': 1000, 'maxlen': 100, 'alpha_entropy_c': 0.002, 'ctx2out': True, 'reload_': False}
Loading data
... loading data
Building model
Buliding sampler
Building f_init... Done
Optimization
Epoch  0
Epoch  0 Update  1 Cost  527.620910645 PD  0.000997066497803 UD  0.72459602356
NaN detected
Traceback (most recent call last):
  File "evaluate_coco.py", line 81, in <module>
    main(defaults)
  File "evaluate_coco.py", line 49, in main
    print "Final cost: {:.2f}".format(validerr.mean())
AttributeError: 'float' object has no attribute 'mean'
```

I am using theano version '0.6.0.dev-8e85dbabd78c3932997aaf840832a1bb5c5835b3'

**Comment by quilby** [comment]
Using an earlier theano commit from Feb 2015 solved this for me. I used commit: b7f4733f47cd9e0f11067a5e67473b5fe7fbf259
